### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by wiebenl** [lodu/TMobile-NL-Unlimited-Bundle-Automated#8]
The script have 2 weeks good worked, and now every time when its run this error.

23:11:08 0|unlimited-sim  | 2023-02-03T23:11:08: TypeError: Cannot read property '0' of undefined
23:11:08 0|unlimited-sim  | 2023-02-03T23:11:08:     at TMobile.handleSubscriptionURL (/home/wiebe/TMobile-NL-Unlimited-Bundle-Automated/dist/providerModels/TMobile/index.js:70:52)
23:11:08 0|unlimited-sim  | 2023-02-03T23:11:08:     at processTicksAndRejections (internal/process/task_queues.js:97:5)
23:11:08 0|unlimited-sim  | 2023-02-03T23:11:08:     at async TMobile.getMBsLeft (/home/wiebe/TMobile-NL-Unlimited-Bundle-Automated/dist/providerModels/TMobile/index.js:97:15)
23:11:08 0|unlimited-sim  | 2023-02-03T23:11:08:     at async run (/home/wiebe/TMobile-NL-Unlimited-Bundle-Automated/dist/index.js:12:21)

What's wrong?

**Comment by ThijsdeZeeuw** [comment]
Same problem

**Comment by lodu** [comment]
See https://gathering.tweakers.net/forum/view_message/74493002

I currently have no plans to dive into the problem since I don't have T-Mobile myself (made this for a friend).
If I see any one else with a fix I will (probably) fix it in this repo as well.
